/**
 * Template
 * Template Web API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MatchDto } from './matchDto';
import { BetDto } from './betDto';
import { ResultDto } from './resultDto';


export interface MatchSelectedDto { 
    id?: string;
    id_match?: string;
    match?: MatchDto;
    bet?: BetDto;
    result?: ResultDto;
    id_result?: string;
    id_bet?: string;
}

