/**
 * Template
 * Template Web API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamDto } from './teamDto';
import { ResultDto } from './resultDto';


export interface MatchDto { 
    id?: string;
    id_team_home?: string;
    id_team_away?: string;
    quote_home?: number;
    quote_away?: number;
    quote_null?: number;
    result?: ResultDto;
    id_result?: string;
    team_home?: TeamDto;
    team_away?: TeamDto;
}

