/**
 * Template
 * Template Web API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResultDto { 
    id?: string;
    value?: ResultDto.ValueEnum;
}
export namespace ResultDto {
    export type ValueEnum = 'home' | 'away' | 'draw' | 'UNSET';
    export const ValueEnum = {
        Home: 'home' as ValueEnum,
        Away: 'away' as ValueEnum,
        Draw: 'draw' as ValueEnum,
        Unset: 'UNSET' as ValueEnum
    };
}


